# This file was generated by GoReleaser. DO NOT EDIT.
class Tldr < Formula
  desc "Simplified and community-driven man pages (tldr-pages)."
  homepage "https://github.com/litianqi1996/tldr-cli"
  version "0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.4/tldr_0.4_Darwin_x86_64.tar.gz"
    sha256 "03cd8484d184eb8cb10e82ac52a548aac1b0b227cb505418610fdd569023d626"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.4/tldr_0.4_Linux_x86_64.tar.gz"
      sha256 "1ecd39907dc298b4544e32f52dbff2ee80e5800a85829aa5ec5e8a8765096beb"
    end
  end

  def install
    bin.install "tldr"
  end

  test do
    system "#{bin}/tldr -version"
  end
end

