# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tldr < Formula
  desc "Simplified and community-driven man pages (tldr-pages)."
  homepage "https://github.com/litianqi1996/tldr-cli"
  version "0.6.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.6.3/tldr_0.6.3_Darwin_arm64.tar.gz"
      sha256 "cd62d4d06c7b9de486d93da1c47c1b70404934a26d81dea4e1c701c81b5bd65a"

      def install
        bin.install "tldr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.6.3/tldr_0.6.3_Darwin_x86_64.tar.gz"
      sha256 "882d4618c543f1eb00270a2272613308973aac7a0cc34629a3bf6e6260993d06"

      def install
        bin.install "tldr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.6.3/tldr_0.6.3_Linux_arm64.tar.gz"
      sha256 "952ded80575a75f861975ce6102969be32a16debeb8b84b668f7e3994d898b58"

      def install
        bin.install "tldr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.6.3/tldr_0.6.3_Linux_x86_64.tar.gz"
      sha256 "e0d6eca2bd4682c818d8dfcc95a69fd68eeac0bdee447d531cbb127e066c2da8"

      def install
        bin.install "tldr"
      end
    end
  end
end
